export const STATUS = {
  IDLE: 'IDLE',
  WORKING: 'WORKING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export const KEY_CODE = {
  TAB: 9,
  ENTER: 13,
  ESC: 27,
  SPACEBAR: 32,
  ARROW_LEFT: 37,
  ARROW_UP: 38,
  ARROW_RIGHT: 39,
  ARROW_DOWN: 40,
};